### ISSUE TITLE
Make it possible to have multiple instances of the keyboard

### ISSUE THREAD

**Issue by jackharrhy** [evnwttn/punch-the-keys#19]
Definitely not easy, but would be a great learning experience

**Comment by evnwttn** [comment]
it's beautiful

![image](https://user-images.githubusercontent.com/85702891/133895658-5e27b9b5-9b10-41a0-a644-04bc02e1168b.png)

**Comment by jackharrhy** [comment]
loves it

**Comment by evnwttn** [comment]
![](https://memegenerator.net/img/instances/39331352/alas-the-deed-is-done-once-more.jpg)

**Comment by evnwttn** [comment]
just realized i have to redo the click functions but the keydowns work on multiple instances once you bring them into focus
