### ISSUE TITLE
style things for the documentation

### ISSUE THREAD

**Issue by jackharrhy** [evnwttn/punch-the-keys#47]
make it open as not expanded, clicking button makes it bigger, can toggle

give background color

make some of the text left aligned

make the code use a monospaced font

<img width="702" alt="Screen Shot 2021-11-03 at 7 02 16 PM" src="https://user-images.githubusercontent.com/6486417/140195871-41e3f189-a6bb-4f77-8862-00c8421c3d9b.png">

make sure the user knows where to put the code

put the script tag in the head

and the element somewhere in the body

reference github from website (bonus: have a little github icon in the top right, maybe using https://vinayakkulkarni.github.io/v-github-icon/?path=/story/github-icon--with-url-prop)

**Comment by evnwttn** [comment]
pretty happy with this now, couple aesthetic tune-ups and it expands/contracts if in/out of focus.
