### ISSUE TITLE
Big monitor = keyboard split in half

### ISSUE THREAD

**Issue by jackharrhy** [evnwttn/punch-the-keys#5]
![Screen Shot 2021-09-04 at 12 11 54 AM](https://user-images.githubusercontent.com/6486417/132079873-376971c5-bc0d-4615-bf92-c057e8e2c22a.png)

Might be a good use for https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

**Comment by evnwttn** [comment]
Will check this out, thanks!

**Comment by evnwttn** [comment]
`#container {
  min-width: 960px;
  max-width: 1885px;
}`

Appears to be the sweet spot, will have to check on a larger monitor but it checks out w/ zoom out.
