### ISSUE TITLE
Not using the physical keyboard does not invoke the sounds

### ISSUE THREAD

**Issue by jackharrhy** [evnwttn/punch-the-keys#6]
Clicking on each key should invoke the same code that will eventually make sounds

**Comment by evnwttn** [comment]
Gotcha, noticed this yesterday. Will check it out today.

**Comment by evnwttn** [comment]
Works now! Still sounds rough but I cleaned the js up a little here for the keydown & clicks.

`const synth = new Tone.PolySynth().toDestination();

document.body.addEventListener("keydown", (e) => {
  let typeKey = getKey(e);
  if (typeKey.hasAttribute("data-sound")) {
    let note = typeKey.getAttribute("data-sound");
    synth.triggerAttackRelease(`${note}4`, "4n");
  } else {
    console.log("no note");
  }
});

const clickKey = document.querySelectorAll(".gdt");
for (let i = 0; i < clickKey.length; i++) {
  clickKey[i].addEventListener("click", function () {
    if (clickKey[i].hasAttribute("data-sound")) {
      let note = clickKey[i].getAttribute("data-sound");
      synth.triggerAttackRelease(`${note}4`, "4n");
    } else {
      console.log("no note");
    }
  });
}`
