### ISSUE TITLE
Give the keys some icons for what they do, like a multiliguinal keyboard

### ISSUE THREAD

**Issue by jackharrhy** [evnwttn/punch-the-keys#8]
![image](https://user-images.githubusercontent.com/6486417/132417426-c9923f56-7842-4d2e-bca8-af51e2f7fb79.png)

**Comment by evnwttn** [comment]
![image](https://user-images.githubusercontent.com/85702891/132912356-893f6d9c-648f-47fd-ba5b-01e734dcf63f.png)
